# Python Numpy Tutorial scribing
This tutorial was contributed by Justin Johnson

In [2]:
import numpy as np

In [6]:
# for z indexem

col = ['red', 'blue', 'black', 'rainbow']

for index, color in enumerate(col):
    print('%d -> %s' % (index, color))

0 -> red
1 -> blue
2 -> black
3 -> rainbow


In [8]:
a = np.array([1,2,3])
a.shape

(3,)

In [14]:
a = np.zeros((2,2,2))
a

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [16]:
a = np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [17]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.random((2,2))

array([[0.15812467, 0.35059601],
       [0.60772144, 0.2788371 ]])

In [22]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [25]:
np.arange(4)

array([], dtype=int64)

In [27]:
x = np.full((2,2),7)
y = np.ones((2,2))
x + y

array([[8., 8.],
       [8., 8.]])

In [28]:
x * y

array([[7., 7.],
       [7., 7.]])

In [30]:
np.sqrt(x/y)

array([[2.64575131, 2.64575131],
       [2.64575131, 2.64575131]])

In [31]:
np.dot(x,y)

array([[14., 14.],
       [14., 14.]])

In [32]:
x.dot(y)

array([[14., 14.],
       [14., 14.]])

In [39]:
a = np.array([[1,2],[3,4]])

a

array([[1, 2],
       [3, 4]])

In [40]:
a.sum()

10

In [37]:
a.sum(axis = 1)

array([3, 7])

In [38]:
a.sum(axis = 0)

array([4, 6])

In [41]:
a.T

array([[1, 3],
       [2, 4]])

In [56]:
v = np.array([10,8])
vv = np.tile(v, (2,1))
vv

array([[10,  8],
       [10,  8]])

In [49]:
np.tile(v, (3,3))

array([[10,  8, 10,  8, 10,  8],
       [10,  8, 10,  8, 10,  8],
       [10,  8, 10,  8, 10,  8]])

In [58]:
x + vv   # można tak

array([[17, 15],
       [17, 15]])

In [60]:
x + v     # ale tak też zadziała

array([[17, 15],
       [17, 15]])

In [64]:
a = np.tile(np.array([1,2,3]), (4,2))
a

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [66]:
b = [1,2,3,4]
a + b
# shape musi się zgadzać!

ValueError: operands could not be broadcast together with shapes (4,6) (4,) 

In [70]:
b = [1,2,3,4,5,6]
a + b
# doda na wszystkich wersach

array([[2, 4, 6, 5, 7, 9],
       [2, 4, 6, 5, 7, 9],
       [2, 4, 6, 5, 7, 9],
       [2, 4, 6, 5, 7, 9]])

In [76]:
np.reshape(a, (6,4))   # liczba elemtntow musi starczyc!

array([[1, 2, 3, 1],
       [2, 3, 1, 2],
       [3, 1, 2, 3],
       [1, 2, 3, 1],
       [2, 3, 1, 2],
       [3, 1, 2, 3]])